const {JSDOM}=require('jsdom');
const {IDBFactory}=require('fake-indexeddb');
const fs=require('fs'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8'),js=fs.readFileSync(require('path').join(__dirname,'../app.js'),'utf8');
const seed={menus:['腕立て','逆手懸垂','<b>種目</b>'],history:[{date:'2026/09/09',time:'10:00',menu:'腕立て',count:24,id:1},{date:'2026/09/01',time:'09:00',menu:'逆手懸垂',count:14,id:1}]};
function setup(db=new IDBFactory(),saved=seed){const dom=new JSDOM(html,{url:'https://yuuuh26.github.io/workout/',runScripts:'outside-only'}),w=dom.window;w.eval=code=>require('vm').runInContext(code,dom.getInternalVMContext());w.indexedDB=db;w.structuredClone=structuredClone;w.navigator.locks={request:async(n,fn)=>fn()};w.navigator.storage={persist:async()=>false,persisted:async()=>false};w.confirm=()=>true;w.alert=()=>{};w.navigator.clipboard={writeText:async t=>w.clip=t};w.URL.createObjectURL=()=>'';w.URL.revokeObjectURL=()=>{};w.localStorage.setItem('pureLocalHistory',JSON.stringify(saved.history));w.localStorage.setItem('pureLocalMenus',JSON.stringify(saved.menus));w.eval(js);w.eval('download=(text,name,type)=>{window.downloads ||= [];window.downloads.push({text,name,type});}');return w;}
async function ready(w){for(let n=0;n<200;n++){if(w.eval('mode')!=='loading')return;await new Promise(r=>setTimeout(r,5));}throw Error('init timeout');}
const plain=x=>JSON.parse(JSON.stringify(x));
(async()=>{const db=new IDBFactory(),w=setup(db);await ready(w);assert.equal(w.eval('mode'),'legacy');w.downloadBackup(true);await w.migrateStorage();assert.equal(w.eval('mode'),'indexeddb');assert.deepEqual(plain(w.eval('state')),seed);assert.deepEqual(JSON.parse(w.localStorage.pureLocalHistory),seed.history);
const reload=setup(db);await ready(reload);assert.deepEqual(plain(reload.eval('state')),seed);
w.document.getElementById('dateDetails').open=true;w.document.getElementById('recordDate').value='2026-08-31T18:30';w.document.getElementById('countInput').value='30';await w.saveRecord();assert.equal(w.eval('state.history[0].date'),'2026/08/31');assert.equal(w.document.getElementById('recordDate').value,'');w.exportMarkdown();assert.equal(w.downloads.at(-1).name,'筋トレ記録_20260831-20260909.md');await w.exportHistory();assert.match(w.clip,/2026\/08\/31/);
w.document.getElementById('countInput').value='11';await w.saveRecord();assert.notEqual(w.eval('state.history[0].date'),'2026/08/31');await w.deleteHistoryItem(2);assert.equal(w.eval('state.history.filter(r=>r.id===1).length'),1);
reload.document.getElementById('countInput').value='9';await reload.saveRecord();assert.match(reload.document.getElementById('appMessage').textContent,/別の画面/);
const before=w.eval('JSON.stringify(state)');w.eval("window.realWrite=writeDB;writeDB=async()=>{throw Error('保存失敗');}");w.document.getElementById('countInput').value='99';await w.saveRecord();assert.equal(w.eval('JSON.stringify(state)'),before);assert.equal(w.document.getElementById('countInput').value,'99');w.eval('writeDB=window.realWrite');await w.requestPersistence();assert.equal(w.eval('mode'),'indexeddb');assert.equal(w.document.querySelectorAll('#bestGrid b').length,0);
// Restore uses the actual file input handler with a File.text-compatible test object.
const file={text:async()=>JSON.stringify({format:'yuu-workout-backup',version:1,...seed})};await w.document.getElementById('restoreFile').onchange({target:{files:[file],value:'x'}});assert.deepEqual(plain(w.eval('state')),seed);
const fail=setup();await ready(fail);fail.downloadBackup(true);fail.eval("writeDB=async()=>{throw Error('移行失敗');}");await fail.migrateStorage();assert.equal(fail.eval('mode'),'legacy');assert.deepEqual(JSON.parse(fail.localStorage.pureLocalHistory),seed.history);
const stale=setup();await ready(stale);stale.downloadBackup(true);stale.localStorage.setItem('pureLocalHistory','[]');await stale.migrateStorage();assert.equal(stale.eval('mode'),'legacy');assert.match(stale.document.getElementById('appMessage').textContent,/再保存/);
console.log('PASS: exact migration, duplicate IDs, legacy retention, reload, historical/current datetime, period filename, clipboard, single deletion, restore, stale-tab conflict, failed save retention, denied persistence, literal HTML, migration failure, stale backup rejection');
[w,reload,fail,stale].forEach(x=>x.close());})();
